<?php

/**
 * @file
 * Contains elfsight_whatsapp_chat.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function elfsight_whatsapp_chat_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {

    case 'help.page.elfsight_whatsapp_chat':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>';
      $output .= t('Visit the <a href=":project_link">Elfsight WhatsApp Chat project pages</a> on Drupal.org for more information.',[
        ':project_link' => 'https://www.drupal.org/project/elfsight_whatsapp_chat'
        ]);
      $output .= '</p>';

      return $output;

    default:
  }
}

